stages:
  - lint
  - test

variables:
  NODE_ENV: test

lint:
  stage: lint
  image: node:22
  before_script:
    - npm ci
  script:
    - npm run lint
  only:
    - merge_requests

test:
  stage: test
  image: node:22
  before_script:
    - npm ci
  script:
    - npm run test
  only:
    - merge_requests

